apiVersion: apps/v1
kind: Deployment
metadata:
  name: coach-player-service
  labels:
    app: coach-player-service
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coach-player-service
  template:
    metadata:
      labels:
        app: coach-player-service
        tier: backend
    spec:
      containers:
      - name: coach-player-service
        image: kingczin/coach_player-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5004
        env:
        - name: MONGODB_URI
          value: "mongodb+srv://user:userpass@dead-drop-db.shfcaup.mongodb.net/Esport?retryWrites=true&w=majority&appName=dead-drop-db"
        - name: JWT_SECRET
          value: "347186591486#^%%ABCF*##GHE"
        - name: PORT
          value: "5004"
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5004
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5004
          initialDelaySeconds: 5
          periodSeconds: 5
