apiVersion: v1
kind: Service
metadata:
  name: coach-player-service
  labels:
    app: coach-player-service
spec:
  selector:
    app: coach-player-service
  ports:
  - name: http
    port: 80
    targetPort: 5004
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: coach-player-service-nodeport
  labels:
    app: coach-player-service
spec:
  selector:
    app: coach-player-service
  ports:
  - name: http
    port: 5004
    targetPort: 5004
    nodePort: 30004
    protocol: TCP
  type: NodePort
