apiVersion: v1
kind: Service
metadata:
  name: registration-service
  labels:
    app: registration-service
spec:
  selector:
    app: registration-service
  ports:
  - name: http
    port: 80
    targetPort: 5001
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: registration-service-nodeport
  labels:
    app: registration-service
spec:
  selector:
    app: registration-service
  ports:
  - name: http
    port: 5001
    targetPort: 5001
    nodePort: 30001
    protocol: TCP
  type: NodePort
