apiVersion: v1
kind: Service
metadata:
  name: ticket-service
  labels:
    app: ticket-service
spec:
  selector:
    app: ticket-service
  ports:
  - name: http
    port: 80
    targetPort: 5005
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: ticket-service-nodeport
  labels:
    app: ticket-service
spec:
  selector:
    app: ticket-service
  ports:
  - name: http
    port: 5005
    targetPort: 5005
    nodePort: 30005
    protocol: TCP
  type: NodePort
